import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from "next/link";
import { useRouter } from "next/router";
import Grid from '@mui/material/Grid';
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css"
import Nav from "../booster/Nav"
import { Container } from '@mui/material';
const domain = process.env.NEXT_PUBLIC_BASE_URL

function BoosterAccount({children}) {
  const router = useRouter();
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "booster") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  return (
    <>
    <Head>
        <title>Center Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        typeof window !== "undefined" && localStorage.getItem("role") !== "booster" ? 
<div></div> : <>
<Nav />
    <Container>
    <div style={{ paddingBottom:"30px"}} className = "boosterDashboardInnerContainer">
      <Grid container columnSpacing={5}>
        <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
        <div id="navScrollHide">

        <div >
          <div className={dashboardCss.mainTitle}>General</div>
          <hr className={dashboardCss.horiLine}/>
            <div
              className={
                currentUrl == `/booster-dashboard/account`
                  ? dashboardCss.sidebarTitleActive
                  : dashboardCss.sidebarTitle
              }
            >
          <Link href="/booster-dashboard/account">
              <a>Basic Info</a>
          </Link>
            </div>
        
        
     
            <div
              className={
                currentUrl.includes("/booster-dashboard/account/notifications")
                  ? dashboardCss.sidebarTitleActive
                  : dashboardCss.sidebarTitle
              }
            >
          <Link href="/booster-dashboard/account/notifications">
              <a>Notifications</a>
          </Link>
            </div>
        </div>
        </div>
                    {/* //nav scroll */}
                    <div className="navScroll">
                    <Link href="/booster-dashboard/account">
                      <a
                        className={
                          currentUrl ==
                            `/booster-dashboard/account`
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Profile
                      </a>
                      </Link>
                      
                   
                      <Link href="/booster-dashboard/account/notifications">
                      <a
                        className={
                         currentUrl.includes(
                            "/booster-dashboard/account/notifications"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Notifications
                      </a>
                      </Link>
                    </div>
        </Grid>
        <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
        <div className={dashboardCss.dashboardRightDiv}>
        {children}
        </div>
        
        </Grid>
      </Grid>
     
    </div>
    </Container></>
}
   
    </>
  )
}

export default BoosterAccount