import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import Nav from "../booster/Nav";
import { Container } from "@mui/material";
const domain = process.env.NEXT_PUBLIC_BASE_URL;

function BoosterActivities({ children }) {
  const router = useRouter();
  let [selectedTab, setSelectedTab] = useState("media");
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  let changeSelectedTab = (tab) => {
    if (selectedTab == tab) {
      setSelectedTab("none");
    } else {
      setSelectedTab(tab);
    }
  };
  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "booster") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  useEffect(() => {
    if (
      currentUrl == `/booster-dashboard/activities` ||
      currentUrl.includes("/booster-dashboard/activities/likes")
    ) {
      setSelectedTab("store");
    } else {
      setSelectedTab("inspired");
    }
  }, [currentUrl]);
  return (
    <>
      <Head>
        <title>Booster Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        typeof window !== "undefined" && localStorage.getItem("role") !== "booster" ? 
<div></div> : <>
<Nav />
      <Container className={`Container`}>
        <div style={{ marginTop:"30px", paddingBottom:"30px"}} className={dashboardCss.marTop}>
          <div>
            <Grid container rowSpacing={0} columnSpacing={7}>
              <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
              <div id="navScrollHide">
                <div>
                 
                  
                  {/* <div onClick={()=>changeSelectedTab("store")}>
                    {
                        selectedTab === "store" ? 
                        <KeyboardArrowUpIcon style={{ float: "right" }} /> : 
                        <KeyboardArrowDownIcon style={{ float: "right" }} />
                    }
                    <div className={dashboardCss.mainTitle}>My Store</div>
                    <hr className={dashboardCss.horiLine} />
                  </div>
                  <div style={{display: selectedTab == "store" ? "block" : "none"}}> */}
                  {/* <Link href="/booster-dashboard/activities">
                      <div
                        className={
                          currentUrl ==
                          `/booster-dashboard/activities`
                          ? dashboardCss.sidebarTitleActive
                          : dashboardCss.sidebarTitle
                        }
                      >
                        Downloaded Shots
                      </div>
                    </Link>
                    <Link href="/booster-dashboard/activities/likes">
                      <div
                        className={
                          currentUrl.includes(
                            "/booster-dashboard/activities/likes"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                        Liked Shots
                      </div>
                    </Link> */}
                   
                  {/* </div> */}
                 
                  <div onClick={()=>changeSelectedTab("inspired")}>
                    {/* {
                        selectedTab == "inspired" ? <KeyboardArrowUpIcon style={{ float: "right" }} /> : <KeyboardArrowDownIcon style={{ float: "right" }} />
                    } */}
                    <div className={dashboardCss.mainTitle} style = {{pointerEvents: "none"}}>Inspired</div>
                    <hr className={dashboardCss.horiLine} />
                  </div>
                  <div >
                      <div
                        className={
                          currentUrl ==
                          `/booster-dashboard/activities`
                          ? dashboardCss.sidebarTitleActive
                          : dashboardCss.sidebarTitle
                        }
                      >
                  <Link href="/booster-dashboard/activities">
                        <a>Downloaded Shots</a>
                    </Link>
                      </div>
                      <div
                        className={
                          currentUrl.includes(
                            "/booster-dashboard/activities/likes"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/booster-dashboard/activities/likes">
                        <a>Liked Shots</a>
                    </Link>
                      </div>
                      <div
                        className={
                          currentUrl.includes(
                            "/booster-dashboard/activities/following"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/booster-dashboard/activities/following">
                        <a>Following</a>
                    </Link>
                      </div>
                      <div
                        className={
                          currentUrl.includes(
                            "/booster-dashboard/activities/bookmarked-centers"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/booster-dashboard/activities/bookmarked-centers">
                        <a>Bookmarked Centres</a>
                    </Link>
                      </div>
                  </div>
                </div>
                </div>
                    {/* //nav scroll */}
                    <div className="navScroll">
                      <Link href="/booster-dashboard/activities">
                        <a className={
                              currentUrl == `/booster-dashboard/activities`
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Downloads</a>
                      </Link>
                     
                      <Link href="/booster-dashboard/activities/likes">
                        <a className={
                              currentUrl.includes(
                                "/booster-dashboard/activities/likes"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Likes</a>
                      </Link>
                  
                      
                      <Link href="/booster-dashboard/activities/following">
                        <a className={
                              currentUrl.includes(
                                "/booster-dashboard/activities/following"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Following</a>
                      </Link>
                      <Link href="/booster-dashboard/activities/bookmarked-centers">
                        <a className={
                              currentUrl.includes(
                                "/booster-dashboard/activities/bookmarked-centers"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Bookmarked Centers</a>
                      </Link>
                    </div>
              </Grid>
              <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                <div className={dashboardCss.dashboardRightDiv}>{children}</div>
              </Grid>
            </Grid>
          </div>
        </div>
      </Container></>
}
     
    </>
  );
}

export default BoosterActivities;
