import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import Nav from "../center/Nav";
import { Container } from "@mui/material";
const domain = process.env.NEXT_PUBLIC_BASE_URL;

function CenterAccount({ children }) {
  const router = useRouter();
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "service_center") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  return (
    <>
      <Head>
        <title>Center Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof window !== "undefined" &&
      localStorage.getItem("role") !== "service_center" ? (
        <div></div>
      ) : (
        <>
          <Nav />
          <Container>
            <div
              style={{ marginTop: "30px", paddingBottom: "30px" }}
              className={dashboardCss.marTop}
            >
              <div>
                <Grid container rowSpacing={0} columnSpacing={7}>
                  <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                    <div id="navScrollHide">
                      <div>
                        <div className={dashboardCss.mainTitle}>General</div>
                        <hr className={dashboardCss.horiLine} />
                        <button
                          className={
                            currentUrl == `/center-dashboard/account`
                              ? dashboardCss.sidebarTitleActive
                              : dashboardCss.sidebarTitle
                          }
                        >
                          <Link href="/center-dashboard/account/">
                            <a>Basic Info</a>
                          </Link>
                        </button>

                        {/* <Link href="/center-dashboard/account/help-center">
            <button
              className={
                currentUrl.includes("/center-dashboard/account/help-center")
                  ? dashboardCss.sidebarTitleActive
                  : dashboardCss.sidebarTitle
              }
            >
              Help Center
            </button>
          </Link> */}
                        <button
                          className={
                            currentUrl.includes(
                              "/center-dashboard/account/notifications"
                            )
                              ? dashboardCss.sidebarTitleActive
                              : dashboardCss.sidebarTitle
                          }
                        >
                          <Link href="/center-dashboard/account/notifications">
                            <a>Notifications</a>
                          </Link>
                        </button>
                      </div>
                    </div>
                    {/* //nav scroll */}
                    <div className="navScroll">
                      <Link href="/center-dashboard/account">
                        <a
                          className={
                            currentUrl == `/center-dashboard/account`
                              ? "navScrollTabActive"
                              : "navScrollTab"
                          }
                        >
                          Profile
                        </a>
                      </Link>

                      <Link href="/center-dashboard/account/notifications">
                        <a
                          className={
                            currentUrl.includes(
                              "/center-dashboard/account/notifications"
                            )
                              ? "navScrollTabActive"
                              : "navScrollTab"
                          }
                        >
                          Notifications
                        </a>
                      </Link>
                    </div>
                  </Grid>
                  <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                    <div className={dashboardCss.dashboardRightDiv}>
                      {children}
                    </div>
                  </Grid>
                </Grid>
              </div>
            </div>
          </Container>
        </>
      )}
    </>
  );
}

export default CenterAccount;
