import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";
import Nav from "../center/Nav";
import { Container } from "@mui/material";
const domain = process.env.NEXT_PUBLIC_BASE_URL;

function CenterActivities({ children }) {
  const router = useRouter();
  let [selectedTab, setSelectedTab] = useState("media");
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  let changeSelectedTab = (tab) => {
    if (selectedTab == tab) {
      setSelectedTab("none");
    } else {
      setSelectedTab(tab);
    }
  };
  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "service_center") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  useEffect(() => {
    if (
      currentUrl == `/center-dashboard/activities` ||
      currentUrl.includes("/center-dashboard/activities/likes")
    ) {
      setSelectedTab("inspired");
    } else if (
      currentUrl.includes("/center-dashboard/activities/center-enquiries")
    ) {
      setSelectedTab("enquiries");
    } else {
      setSelectedTab("inspired");
    }
  }, [currentUrl]);
  return (
    <>
      <Head>
        <title>Center Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof window !== "undefined" &&
      localStorage.getItem("role") !== "service_center" ? (
        <div></div>
      ) : (
        <>
          <Nav />
          <Container className={`Container`}>
            <div style={{ marginTop: "30px", paddingBottom: "30px" }} className={dashboardCss.marTop}>
              <div>
                <Grid container rowSpacing={0} columnSpacing={7}>
                  <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                  <div id="navScrollHide">
                    <div>
                      {/* <div onClick={() => changeSelectedTab("store")}>
                        {selectedTab === "store" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div className={dashboardCss.mainTitle}>My Store</div>
                        <hr className={dashboardCss.horiLine} />
                      </div> */}
                      {/* <div
                        style={{
                          display: selectedTab == "store" ? "block" : "none",
                        }}
                      >
                        <Link href="/center-dashboard/activities">
                          <button
                            className={
                              currentUrl ==
                                `/center-dashboard/activities`
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            Downloaded Shots
                          </button>
                        </Link>
                        <Link href="/center-dashboard/activities/likes">
                          <button
                            className={
                              currentUrl.includes(
                                "/center-dashboard/activities/likes"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            Liked Shots
                          </button>
                        </Link>
                      </div> */}
                      
                      <div onClick={() => changeSelectedTab("inspired")}>
                        {selectedTab == "inspired" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div className={dashboardCss.mainTitle}>Inspired</div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      <div
                        style={{
                          display: selectedTab == "inspired" ? "block" : "none",
                        }}
                      >
                          <button
                            className={
                              currentUrl ==
                                `/center-dashboard/activities`
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/center-dashboard/activities">
                            <a>Downloaded Shots</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/center-dashboard/activities/likes"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/center-dashboard/activities/likes">
                            <a>Liked Shots</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/center-dashboard/activities/following"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/center-dashboard/activities/following">
                            <a>Following</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/center-dashboard/activities/bookmarked-centers"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/center-dashboard/activities/bookmarked-centers">
                            <a>Bookmarked Centers</a>
                        </Link>
                          </button>
                      </div>
                      <div onClick={() => changeSelectedTab("enquiries")}>
                        {selectedTab == "enquiries" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div className={dashboardCss.mainTitle}>Enquiries</div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      <div
                        style={{
                          display:
                            selectedTab == "enquiries" ? "block" : "none",
                        }}
                      >
                          <button
                            className={
                              currentUrl.includes(
                                "/center-dashboard/activities/center-enquiries"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/center-dashboard/activities/center-enquiries">
                            <a>Center Enquiries</a>
                        </Link>
                          </button>
                      </div>
                    </div>
                    </div>
                    {/* //nav scroll */}
                    <div className="navScroll">
                      <Link href="/center-dashboard/activities">
                        <a className={
                              currentUrl == `/center-dashboard/activities`
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Downloads</a>
                      </Link>
                     
                      <Link href="/center-dashboard/activities/likes">
                        <a className={
                              currentUrl.includes(
                                "/center-dashboard/activities/likes"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Likes</a>
                      </Link>
                      <Link href="/center-dashboard/activities/center-enquiries">
                        <a className={
                              currentUrl.includes(
                                "/center-dashboard/activities/center-enquiries"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Enquiries</a>
                      </Link>
                      
                      
                      <Link href="/center-dashboard/activities/following">
                        <a className={
                              currentUrl.includes(
                                "/center-dashboard/activities/following"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Following</a>
                      </Link>
                      <Link href="/center-dashboard/activities/bookmarked-centers">
                        <a className={
                              currentUrl.includes(
                                "/center-dashboard/activities/bookmarked-centers"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Bookmarked Centers</a>
                      </Link>
                    </div>
                  </Grid>
                  <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                    <div className={dashboardCss.dashboardRightDiv}>
                      {children}
                    </div>
                  </Grid>
                </Grid>
              </div>
            </div>
          </Container>
        </>
      )}
    </>
  );
}

export default CenterActivities;
