import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Nav from "../company/nav";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import { Container } from "@mui/material";
const domain = process.env.NEXT_PUBLIC_BASE_URL;

function CompanyActivities({ children }) {
  const router = useRouter();
    let [selectedTab, setSelectedTab] = useState("media")
    let changeSelectedTab = (tab) =>{
      if(selectedTab == tab){
        setSelectedTab("none")
      }else{
        setSelectedTab(tab)
      }
        
    }
    let [currentUrl, setCurrentUrl] = useState("")
    useEffect(()=>{
      setCurrentUrl(router.pathname)
      console.log(router.pathname)
      if(!localStorage.getItem("access_token")){
        router.push("/login")
      }
      else if(localStorage.getItem("role") !== "company"){
        router.push("/NoComponent")
      }
    },[router.pathname])

    useEffect(() => {
      if (
        currentUrl == `/company-dashboard/activities` ||
        currentUrl.includes("/company-dashboard/activities/saved-pilots") ||
        currentUrl.includes("/company-dashboard/activities/sent-proposals")
      ) {
        setSelectedTab("media");
      } else if (
        currentUrl.includes("/company-dashboard/activities/downloads") ||
        currentUrl.includes("/company-dashboard/activities/likes")
      ) {
        setSelectedTab("inspired");
      }  else {
        setSelectedTab("inspired");
      }
    }, [currentUrl]);
  return (
    <>
      <Head>
        <title>Pilot Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        typeof window !== "undefined" && localStorage.getItem("role") !== "company" ? 
<div></div> : <>
<Nav />
      <Container maxWidth={"xxl"}>
        <div style={{ marginTop:"30px", paddingBottom:"30px"}} className={dashboardCss.marTop}>
          <div>
            <Grid container rowSpacing={0} columnSpacing={7}>
              <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
              <div id="navScrollHide">

                <div>
                  <div onClick={()=>changeSelectedTab("media")}>
                    {
                        selectedTab === "media" ? 
                        <KeyboardArrowUpIcon style={{ float: "right" }} /> : 
                        <KeyboardArrowDownIcon style={{ float: "right" }} />
                    }
                    
                    <div className={dashboardCss.mainTitle}>Jobs</div>
                    <hr className={dashboardCss.horiLine} />
                  </div>
                  <div style={{display: selectedTab == "media" ? "block" : "none"}}>
                      <button
                        className={
                          currentUrl ==
                            `/company-dashboard/activities`
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/company-dashboard/activities">
                      <a>
                        Posted Jobs
                      </a>
                    </Link>
                      </button>
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/sent-proposals"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/company-dashboard/activities/sent-proposals">
                      <a>
                        Direct Hires
                      </a>
                    </Link>
                      </button>
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/saved-pilots"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/company-dashboard/activities/saved-pilots">
                      <a>
                        Saved Pilots
                      </a>
                    </Link>
                      </button>
                   
                  </div>
                  {/* <div onClick={()=>changeSelectedTab("store")}>
                    {
                        selectedTab === "store" ? 
                        <KeyboardArrowUpIcon style={{ float: "right" }} /> : 
                        <KeyboardArrowDownIcon style={{ float: "right" }} />
                    }
                    <div className={dashboardCss.mainTitle}>My Store</div>
                    <hr className={dashboardCss.horiLine} />
                  </div>
                  <div style={{display: selectedTab == "store" ? "block" : "none"}}>
                  <Link href="/company-dashboard/activities/downloads">
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/downloads"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                        Downloaded Shots
                      </button>
                    </Link>
                    <Link href="/company-dashboard/activities/likes">
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/likes"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                        Liked Shots
                      </button>
                    </Link>
                   
                  </div> */}

                  <div onClick={()=>changeSelectedTab("inspired")}>
                    {
                        selectedTab == "inspired" ? <KeyboardArrowUpIcon style={{ float: "right" }} /> : <KeyboardArrowDownIcon style={{ float: "right" }} />
                    }
                    <div className={dashboardCss.mainTitle}>Inspired</div>
                    <hr className={dashboardCss.horiLine} />
                  </div>
                  <div style={{display: selectedTab == "inspired" ? "block" : "none"}}>
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/downloads"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                  <Link href="/company-dashboard/activities/downloads">
                    <a>
                        Downloaded Shots
                    </a>
                    </Link>
                      </button>
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/likes"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/company-dashboard/activities/likes">
                      <a>
                        Liked Shots
                      </a>
                    </Link>
                      </button>
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/following"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/company-dashboard/activities/following">
                        Following
                    </Link>
                      </button>
                      <button
                        className={
                          currentUrl.includes(
                            "/company-dashboard/activities/bookmarked-centers"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                    <Link href="/company-dashboard/activities/bookmarked-centers">
                        Bookmarked Centers
                    </Link>
                      </button>
                  </div>
                </div>
                </div>
                {/* //nav scroll */}
                <div className="navScroll">
                      <Link href="/company-dashboard/activities">
                        <a className={
                              currentUrl == `/company-dashboard/activities`
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Uploaded Jobs</a>
                      </Link>
                      <Link href="/company-dashboard/activities/saved-pilots">
                        <a className={
                              currentUrl.includes(
                                "/company-dashboard/activities/saved-pilots"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Saved Pilots</a>
                      </Link>
                      <Link href="/company-dashboard/activities/sent-proposals">
                        <a className={
                              currentUrl.includes(
                                "/company-dashboard/activities/sent-proposals"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Sent Proposals</a>
                      </Link>
                      <Link href="/company-dashboard/activities/downloads">
                        <a className={
                              currentUrl.includes(
                                "/company-dashboard/activities/downloads"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Downloads</a>
                      </Link>
                      <Link href="/company-dashboard/activities/likes">
                        <a className={
                              currentUrl.includes(
                                "/company-dashboard/activities/likes"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Likes</a>
                      </Link>
                      
                      
                      <Link href="/company-dashboard/activities/following">
                        <a className={
                              currentUrl.includes(
                                "/company-dashboard/activities/following"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Following</a>
                      </Link>
                      <Link href="/company-dashboard/activities/bookmarked-centers">
                        <a className={
                          currentUrl.includes(
                            "/company-dashboard/activities/bookmarked-centers"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }>Bookmarked Centers</a>
                      </Link>
                    </div>
              </Grid>
              <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                <div className={dashboardCss.dashboardRightDiv}>{children}</div>
              </Grid>
            </Grid>
          </div>
        </div>
      </Container></>
}
    
    </>
  );
}

export default CompanyActivities;
