import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Nav from "../company/nav";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import { Container } from "@mui/material";
const domain = process.env.NEXT_PUBLIC_BASE_URL;

function CompanyAccount({ children }) {
  const router = useRouter();
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "company") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  return (
    <>
      <Head>
        <title>Company Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof window !== "undefined" &&
      localStorage.getItem("role") !== "company" ? (
        <div></div>
      ) : (
        <>
          <Nav />
          <Container maxWidth = {"xxl"}>
            <div style={{ marginTop: "30px", paddingBottom: "20px" }} className={dashboardCss.marTop}>
              <div>
                <Grid container rowSpacing={0} columnSpacing={7}>
                  <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                    <div id="navScrollHide">
                      <div>
                        <button className={dashboardCss.mainTitle}>
                          General
                        </button>
                        <hr className={dashboardCss.horiLine} />
                          <div
                            className={
                              currentUrl == `/company-dashboard/account`
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/company-dashboard/account/">
                            <a>Profile Information</a>
                        </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/page-information"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/company-dashboard/account/page-information">
                            <a>Company Information</a>
                        </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/subscription"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        {/* <Link href="/company-dashboard/account/subscription">
                            <a>My Subscription</a>
                        </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/billing"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/company-dashboard/account/billing">
                            <a>Billing Address</a>
                        </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/help-center"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          > */}
                        {/* <Link href="/company-dashboard/account/help-center">
                            <a>Help Center</a>
                        </Link> */}
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/notifications"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/company-dashboard/account/notifications">
                            <a>Notifications</a>
                        </Link>
                          </div>
                      </div>
                      </div>
                      {/* //nav scroll */}
                      <div className="navScroll">
                        <Link href="/company-dashboard/account">
                          <a
                            className={
                              currentUrl == `/company-dashboard/account`
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }
                          >
                            Profile
                          </a>
                        </Link>
                        <Link href="/company-dashboard/account/page-information">
                          <a
                            className={
                              currentUrl == `/company-dashboard/account/page-information`
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }
                          >
                            Company Information
                          </a>
                        </Link>
                        <Link href="/company-dashboard/account/billing">
                          <a
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/billing"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }
                          >
                            Billing
                          </a>
                        </Link>
                        <Link href="/company-dashboard/account/subscription">
                          <a
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/subscription"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }
                          >
                            Subscription
                          </a>
                        </Link>
                        <Link href="/company-dashboard/account/help-center">
                          <a
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/help-center"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }
                          >
                            Help
                          </a>
                        </Link>
                        <Link href="/company-dashboard/account/notifications">
                          <a
                            className={
                              currentUrl.includes(
                                "/company-dashboard/account/notifications"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }
                          >
                            Notifications
                          </a>
                        </Link>
                      </div>
            
                  </Grid>
                  <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                    <div className={dashboardCss.dashboardRightDiv}>
                      {children}
                    </div>
                  </Grid>
                </Grid>
              </div>
            </div>
          </Container>
        </>
      )}
    </>
  );
}

export default CompanyAccount;
