import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Router from "next/router";
import Nav from "../pilot/Nav";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";
import { Container } from "@mui/material";
const domain = process.env.NEXT_PUBLIC_BASE_URL;

function PilotActivities({ children }) {
  const router = useRouter();
  let [selectedTab, setSelectedTab] = useState("media");
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  let changeSelectedTab = (tab) => {
    if (selectedTab == tab) {
      setSelectedTab("none");
    } else {
      setSelectedTab(tab);
    }
  };
  useEffect(() => {
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "pilot") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  useEffect(() => {
    if (
      currentUrl == `/pilot-dashboard/activities` ||
      currentUrl.includes("/pilot-dashboard/activities/3d") ||
      currentUrl.includes("/pilot-dashboard/activities/videos")
    ) {
      setSelectedTab("media");
    } else if (
      currentUrl.includes("/pilot-dashboard/activities/downloads") ||
      currentUrl.includes("/pilot-dashboard/activities/likes")
    ) {
      setSelectedTab("inspired");
    } else if (
      currentUrl.includes("/pilot-dashboard/activities/applied-jobs") ||
      currentUrl.includes("/pilot-dashboard/activities/saved-jobs") ||
      currentUrl.includes("/pilot-dashboard/activities/hire-proposals")
    ) {
      setSelectedTab("jobs");
    } else {
      setSelectedTab("inspired");
    }
  }, [currentUrl]);
  return (
    <>
      <Head>
        <title>Pilot Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof window !== "undefined" &&
      localStorage.getItem("role") !== "pilot" ? (
        <div></div>
      ) : (
        <>
          <Nav />
          <Container maxWidth={"xxl"}>
            <div style={{ marginTop: "30px", paddingBottom: "30px" }} id="navMarginTop">
              <div>
                <Grid container rowSpacing={0} columnSpacing={7}>
                  <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                  <div id="navScrollHide">
                    <div>
                      <div onClick={() => changeSelectedTab("media")}>
                        {selectedTab === "media" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}

                        <div className={dashboardCss.mainTitle}>My shots</div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      <div
                        style={{
                          display: selectedTab == "media" ? "block" : "none",
                        }}
                      >
                          <button
                            className={
                              currentUrl == `/pilot-dashboard/activities`
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities">
                          <a>
                            Images
                          </a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/3d"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/3d">
                          <a>
                            3D Models
                          </a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/videos"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/videos">
                          <a>
                            Videos
                          </a>
                        </Link>
                          </button>
                      </div>
                      {/* <div onClick={() => changeSelectedTab("store")}>
                        {selectedTab === "store" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div className={dashboardCss.mainTitle}>My Store</div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      <div
                        style={{
                          display: selectedTab == "store" ? "block" : "none",
                        }}
                      > */}
                        {/* <Link href="/pilot-dashboard/activities/downloads">
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/downloads"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            Downloaded Shots
                          </button>
                        </Link>
                        <Link href="/pilot-dashboard/activities/likes">
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/likes"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            Liked Shots
                          </button>
                        </Link> */}
                      {/* </div> */}
                      <div onClick={() => changeSelectedTab("jobs")}>
                        {selectedTab == "jobs" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}

                        <div className={dashboardCss.mainTitle}>Jobs</div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      <div
                        style={{
                          display: selectedTab == "jobs" ? "block" : "none",
                        }}
                      >
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/applied-jobs"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/applied-jobs">
                            <a>Applied Jobs</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/saved-jobs"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/saved-jobs">
                            <a>Saved Jobs</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/hire-proposals"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/hire-proposals">
                          <a>
                            Hire Proposals
                          </a>
                        </Link>
                          </button>
                      </div>
                      <div onClick={() => changeSelectedTab("inspired")}>
                        {selectedTab == "inspired" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div className={dashboardCss.mainTitle}>Inspired</div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      <div
                        style={{
                          display: selectedTab == "inspired" ? "block" : "none",
                        }}
                      >
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/downloads"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/downloads">
                          <a>
                            Downloaded Shots
                          </a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/likes"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/likes">
                          <a>
                            Liked Shots
                          </a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/followers"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/followers">
                          <a>
                            Followers
                          </a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/following"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/following">
                            <a>Following</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/bookmarked-centers"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                        <Link href="/pilot-dashboard/activities/bookmarked-centers">
                            <a>Bookmarked Centers</a>
                        </Link>
                          </button>
                          <button
                            className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/enquired-courses"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            <Link href="/pilot-dashboard/activities/enquired-courses">
                                <a>Enquired courses</a>
                            </Link>
                          </button>
                      </div>
                    </div>
                    </div>
                    {/* //nav scroll */}
                    <div className="navScroll">
                      <Link href="/pilot-dashboard/activities">
                        <a className={
                              currentUrl == `/pilot-dashboard/activities`
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Uploaded Images</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/3d">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/3d"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>3D Models</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/videos">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/videos"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Videos</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/downloads">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/downloads"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Downloads</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/likes">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/likes"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Likes</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/applied-jobs">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/applied-jobs"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Applied Jobs</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/saved-jobs">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/saved-jobs"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Saved Jobs</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/hire-proposals">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/hire-proposals"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Hire Proposals</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/followers">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/followers"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Followers</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/following">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/following"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Following</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/bookmarked-centers">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/bookmarked-centers"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Bookmarked Centers</a>
                      </Link>
                      <Link href="/pilot-dashboard/activities/enquired-courses">
                        <a className={
                              currentUrl.includes(
                                "/pilot-dashboard/activities/enquired-courses"
                              )
                                ? "navScrollTabActive"
                                : "navScrollTab"
                            }>Enquired courses</a>
                      </Link>
                    </div>
                  </Grid>
                  <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                    <div className={dashboardCss.dashboardRightDiv}>
                      {children}
                    </div>
                  </Grid>
                </Grid>
              </div>
            </div>
          </Container>
        </>
      )}
    </>
  );
}

export default PilotActivities;
