import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Nav from "../pilot/Nav";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import { Container } from "@mui/material";
import axios from "axios";

const domain = process.env.NEXT_PUBLIC_LOCALHOST;
function PilotAccount({ children }) {
  const router = useRouter();
  let [currentUrl, setCurrentUrl] = useState(router.pathname);
  let [subscribed, setSubscribed] = useState(false)

  useEffect(() => {
    const config = {
      headers: {
        Authorization: "Bearer " + localStorage.getItem("access_token"),
      },
    };
    axios
      .get(`${domain}/api/pilotSubscription/getMySubscriptionData`, config)
      .then((res) => {
        if (res.data !== "No Subscription"){
          setSubscribed(true)
        }else{
          setSubscribed(false)
        }
      })
      .catch(err => {
        setSubscribed(false)
      })
    if (!localStorage.getItem("access_token")) {
      router.push("/login");
    } else if (localStorage.getItem("role") !== "pilot") {
      router.push("/NoComponent");
    }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  return (
    <>
      <Head>
        <title>Pilot Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {typeof window !== "undefined" &&
      localStorage.getItem("role") !== "pilot" ? (
        <div></div>
      ) : (
        <>
          <Nav />
          <Container maxWidth={"xxl"}>
            <div style={{ marginTop: "30px", paddingBottom: "30px"}} id="navMarginTop">
              <div>
                <Grid container rowSpacing={0} columnSpacing={7}>
                  <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                    <div id="navScrollHide">
                    <div>
                      <div className={dashboardCss.mainTitle}>General</div>
                      <hr className={dashboardCss.horiLine} />
                        <button
                          className={
                            currentUrl ==
                              `/pilot-dashboard/account`
                              ? dashboardCss.sidebarTitleActive
                              : dashboardCss.sidebarTitle
                          }
                        >
                      <Link href="/pilot-dashboard/account/">
                        <a>
                          Profile Information
                        </a>
                      </Link>
                        </button>
                        <button
                          className={
                           currentUrl.includes(
                              "/pilot-dashboard/account/work"
                            )
                              ? dashboardCss.sidebarTitleActive
                              : dashboardCss.sidebarTitle
                          }
                        >
                      <Link href="/pilot-dashboard/account/work">
                          <a>
                            Work Information

                          </a>
                      </Link>
                        </button>
                      {
                        false &&
                        <>
                            <button
                              className={
                                currentUrl.includes(
                                  "/pilot-dashboard/account/subscription"
                                )
                                  ? dashboardCss.sidebarTitleActive
                                  : dashboardCss.sidebarTitle
                              }
                            >
                          <Link href="/pilot-dashboard/account/subscription">
                            <a>
                              My Subscription
                            </a>
                          </Link>
                            </button>
                        
                            <button
                              className={
                              currentUrl.includes(
                                  "/pilot-dashboard/account/billing"
                                )
                                  ? dashboardCss.sidebarTitleActive
                                  : dashboardCss.sidebarTitle
                              }
                            >
                          <Link href="/pilot-dashboard/account/billing">
                            <a>
                              Billing Address
                            </a>
                          </Link>
                            </button>
                        </>
                      }
                      {/* <Link href="/pilot-dashboard/account/help-center">
                        <button
                          className={
                            currentUrl.includes(
                              "/pilot-dashboard/account/help-center"
                            )
                              ? dashboardCss.sidebarTitleActive
                              : dashboardCss.sidebarTitle
                          }
                        >
                          Help Center
                        </button>
                      </Link> */}
                        <button
                          className={
                            currentUrl.includes(
                              "/pilot-dashboard/account/notifications"
                            )
                              ? dashboardCss.sidebarTitleActive
                              : dashboardCss.sidebarTitle
                          }
                        >
                      <Link href="/pilot-dashboard/account/notifications">
                        <a>
                          Notification settings
                        </a>
                      </Link>
                        </button>
                    </div>
                    </div>
                    {/* //nav scroll */}
                    <div className="navScroll">
                      <div
                        className={
                          currentUrl ==
                            `/pilot-dashboard/account`
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                    <Link href="/pilot-dashboard/account">
                      <a>
                        Profile
                      </a>
                      </Link>
                      </div>
                      <div
                        className={
                          currentUrl.includes(
                            "/pilot-dashboard/account/work"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                      <Link href="/pilot-dashboard/account/work">
                        <a>
                        Work Information
                        </a>
                      </Link>
                      </div>
                      <div
                        className={
                          currentUrl.includes(
                            "/pilot-dashboard/account/billing"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                      <Link href="/pilot-dashboard/account/billing">
                        <a>
                        Billing
                        </a>
                      </Link>
                      </div>
                      <div
                        className={
                          currentUrl.includes(
                            "/pilot-dashboard/account/subscription"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                      <Link href="/pilot-dashboard/account/subscription">
                        <a>
                          Subscription
                        </a>
                      </Link>
                      </div>
                     
                      <div
                        className={
                         currentUrl.includes(
                            "/pilot-dashboard/account/notifications"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                      <Link href="/pilot-dashboard/account/notifications">
                        <a>
                          Notification settings
                        </a>
                      </Link>
                      </div>
                    </div>
                  </Grid>
                  <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                    <div className={dashboardCss.dashboardRightDiv}>
                      {children}
                    </div>
                  </Grid>
                </Grid>
              </div>
            </div>
          </Container>
        </>
      )}
    </>
  );
}

export default PilotAccount;
