import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Grid from "@mui/material/Grid";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import Nav from "../trainingCenter/Nav";
import { Container } from "@mui/material";

function TrainingCenterAccount({ children }) {
  const router = useRouter();
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  useEffect(() => {
    // if (!localStorage.getItem("access_token")) {
    //   router.push("/login");
    // } else if (localStorage.getItem("role") !== "booster") {
    //   router.push("/NoComponent");
    // }
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  return (
    <>
      <Head>
        <title>Center Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <>
          <Nav />
          <Container maxWidth = "xxl">
            <div
              style={{ paddingBottom: "30px" }}
              className="boosterDashboardInnerContainer"
            >
              <Grid container columnSpacing={5}>
                <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                  <div id="navScrollHide">
                    <div>
                      <div className={dashboardCss.mainTitle}>General</div>
                      <hr className={dashboardCss.horiLine} />
                      <div
                        className={
                          currentUrl == `/training-center-dashboard/account`
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                        <Link href="/training-center-dashboard/account">
                          <a>Basic Info</a>
                        </Link>
                      </div>

                      <div
                        className={
                          currentUrl.includes(
                            "/training-center-dashboard/account/notifications"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                        <Link href="/training-center-dashboard/account/notifications">
                          <a>Notifications</a>
                        </Link>
                      </div>
                    </div>
                  </div>
                  {/* //nav scroll */}
                  <div className="navScroll">
                    <Link href="/training-center-dashboard/account">
                      <a
                        className={
                          currentUrl == `/training-center-dashboard/account`
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Profile
                      </a>
                    </Link>

                    <Link href="/training-center-dashboard/account/notifications">
                      <a
                        className={
                          currentUrl.includes(
                            "/training-center-dashboard/account/notifications"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Notifications
                      </a>
                    </Link>
                  </div>
                </Grid>
                <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                  <div className={dashboardCss.dashboardRightDiv}>
                    {children}
                  </div>
                </Grid>
              </Grid>
            </div>
          </Container>
        </>
    </>
  );
}

export default TrainingCenterAccount;
