import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Grid from "@mui/material/Grid";
import global from "../../styles/all.module.css";
import dashboardCss from "../../styles/DashboardSidebar.module.css";
import KeyboardArrowDownIcon from "@mui/icons-material/KeyboardArrowDown";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";
import Nav from "../trainingCenter/Nav";
import { Container } from "@mui/material";

function TrainingCenterActivities({ children }) {
  const router = useRouter();
  let [selectedTab, setSelectedTab] = useState("media");
  let [currentUrl, setCurrentUrl] = useState(router.pathname);

  let changeSelectedTab = (tab) => {
    if (selectedTab == tab) {
      setSelectedTab("none");
    } else {
      setSelectedTab(tab);
    }
  };
  useEffect(() => {
    setCurrentUrl(router.pathname);
  }, [router.pathname]);
  useEffect(() => {
    if (
      currentUrl == `/training-center-dashboard/activities` || currentUrl.includes("/training-center-dashboard/activities/course/enquiries")
    ) {
      setSelectedTab("courses");
    } else {
      setSelectedTab("inspired");
    }
  }, [currentUrl]);
  return (
    <>
      <Head>
        <title>Training center Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Nav />
        <Container maxWidth="xxl">
          <div
            style={{ marginTop: "30px", paddingBottom: "30px" }}
            className={dashboardCss.marTop}
          >
            <div>
              <Grid container rowSpacing={0} columnSpacing={7}>
                <Grid item xxl={3} xl={3} lg={3} md={4} sm={12} xs={12}>
                  <div id="navScrollHide">
                    <div>
                      {/* <div onClick={()=>changeSelectedTab("store")}>
                    {
                        selectedTab === "store" ? 
                        <KeyboardArrowUpIcon style={{ float: "right" }} /> : 
                        <KeyboardArrowDownIcon style={{ float: "right" }} />
                    }
                    <div className={dashboardCss.mainTitle}>My Store</div>
                    <hr className={dashboardCss.horiLine} />
                  </div>
                  <div style={{display: selectedTab == "store" ? "block" : "none"}}> */}
                      {/* <Link href="/training-center-dashboard/activities">
                      <div
                        className={
                          currentUrl ==
                          `/training-center-dashboard/activities`
                          ? dashboardCss.sidebarTitleActive
                          : dashboardCss.sidebarTitle
                        }
                      >
                        Downloaded Shots
                      </div>
                    </Link>
                    <Link href="/training-center-dashboard/activities/likes">
                      <div
                        className={
                          currentUrl.includes(
                            "/training-center-dashboard/activities/likes"
                          )
                            ? dashboardCss.sidebarTitleActive
                            : dashboardCss.sidebarTitle
                        }
                      >
                        Liked Shots
                      </div>
                    </Link> */}

                      {/* </div> */}

                      <div onClick={() => changeSelectedTab("courses")}>
                        {selectedTab == "courses" || currentUrl.includes("/training-center-dashboard/activities/course/enquiries") ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div
                          className={dashboardCss.mainTitle}
                          style={{ pointerEvents: "none" }}
                        >
                          Courses
                        </div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      {selectedTab == "courses" && (
                        <div>
                          <div
                            className={
                              currentUrl ==
                              `/training-center-dashboard/activities` || currentUrl.includes("/training-center-dashboard/activities/course/enquiries")
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            <Link href="/training-center-dashboard/activities">
                              <a>My Courses</a>
                            </Link>
                          </div>
                        </div>
                      )}

                      <div onClick={() => changeSelectedTab("inspired")}>
                        {selectedTab == "inspired" ? (
                          <KeyboardArrowUpIcon style={{ float: "right" }} />
                        ) : (
                          <KeyboardArrowDownIcon style={{ float: "right" }} />
                        )}
                        <div
                          className={dashboardCss.mainTitle}
                          style={{ pointerEvents: "none" }}
                        >
                          Inspired
                        </div>
                        <hr className={dashboardCss.horiLine} />
                      </div>
                      {selectedTab == "inspired" && (
                        <div>
                          <div
                            className={
                              currentUrl ==
                              `/training-center-dashboard/activities/downloads`
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            <Link href="/training-center-dashboard/activities/downloads">
                              <a>Downloaded Shots</a>
                            </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/training-center-dashboard/activities/likes"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            <Link href="/training-center-dashboard/activities/likes">
                              <a>Liked Shots</a>
                            </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/training-center-dashboard/activities/following"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            <Link href="/training-center-dashboard/activities/following">
                              <a>Following</a>
                            </Link>
                          </div>
                          <div
                            className={
                              currentUrl.includes(
                                "/training-center-dashboard/activities/bookmarked-centers"
                              )
                                ? dashboardCss.sidebarTitleActive
                                : dashboardCss.sidebarTitle
                            }
                          >
                            <Link href="/training-center-dashboard/activities/bookmarked-centers">
                              <a>Bookmarked Centres</a>
                            </Link>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                  {/* //nav scroll */}
                  <div className="navScroll">
                    <Link href="/training-center-dashboard/activities">
                      <a
                        className={
                          currentUrl == `/training-center-dashboard/activities` || currentUrl.includes("/training-center-dashboard/activities/course/enquiries")
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        My Courses
                      </a>
                    </Link>
                    <Link href="/training-center-dashboard/activities/downloads">
                      <a
                        className={
                          currentUrl == `/training-center-dashboard/activities/downloads`
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Downloads
                      </a>
                    </Link>

                    <Link href="/training-center-dashboard/activities/likes">
                      <a
                        className={
                          currentUrl.includes(
                            "/training-center-dashboard/activities/likes"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Likes
                      </a>
                    </Link>

                    <Link href="/training-center-dashboard/activities/following">
                      <a
                        className={
                          currentUrl.includes(
                            "/training-center-dashboard/activities/following"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Following
                      </a>
                    </Link>
                    <Link href="/training-center-dashboard/activities/bookmarked-centers">
                      <a
                        className={
                          currentUrl.includes(
                            "/training-center-dashboard/activities/bookmarked-centers"
                          )
                            ? "navScrollTabActive"
                            : "navScrollTab"
                        }
                      >
                        Bookmarked Centers
                      </a>
                    </Link>
                  </div>
                </Grid>
                <Grid item xxl={9} xl={9} lg={9} md={8} sm={12} xs={12}>
                  <div className={dashboardCss.dashboardRightDiv}>
                    {children}
                  </div>
                </Grid>
              </Grid>
            </div>
          </div>
        </Container>
      </>
    </>
  );
}

export default TrainingCenterActivities;
